### ISSUE TITLE
CocoaPods compatibility 

### ISSUE THREAD

**Issue by serejahh** [RxSwiftCommunity/NSObject-Rx#16]
Please, bump tag to use CocoaPods spec

**Comment by ashfurrow** [comment]
Hey, sorry about that! Totally slipped past me, push to CocoaPods trunk now.

**Comment by ashfurrow** [comment]
OK, should be good to go now :+1: Let me know if that works.

**Comment by serejahh** [comment]
Thank you for the quick response. Now it works properly
