### ISSUE TITLE
Issue when uploading to iTunes Connect

### ISSUE THREAD

**Issue by dccarmo** [RxSwiftCommunity/NSObject-Rx#19]
`ERROR ITMS-90205: "Invalid Bundle. The bundle at '../Frameworks/NSObject_Rx.framework' contains disallowed nested bundles."`

Using Carthage.

If I remove NSObject_Rx.framework from `copy-frameworks` script it works fine on Debug schema, but not on Release.

**Comment by dccarmo** [comment]
As a workaround I tried [this](http://stackoverflow.com/a/27362987) and it worked, iTunes Connect accepted my build.

**Comment by ashfurrow** [comment]
Interesting! Thanks for following-up with the solution, I really appreciate that. Since it seems to be addressed, I'm going to close this issue.
