### ISSUE TITLE
How to deinit UIViewController when using rx_disposeBag

### ISSUE THREAD

**Issue by tuannguyenanh177** [RxSwiftCommunity/NSObject-Rx#21]
I have demo project with viewcontroller code here. When I click back barButtonItem but deinit not call. How to deinit UIViewController when using rx_disposeBag?

> class ViewController: BaseViewController {
>     @IBOutlet weak var backButton: UIBarButtonItem!
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
> ```
>     // Do any additional setup after loading the view.
>     self.setupRxButton()
> }
> 
> deinit {
>     print("ViewController deinit")
> }
> 
> override func didReceiveMemoryWarning() {
>     super.didReceiveMemoryWarning()
>     // Dispose of any resources that can be recreated.
> }
> 
> func setupRxButton() {
>     self.backButton
>         .rx_tap
>         .subscribeNext {
>             self.navigationController?.popViewControllerAnimated(true)
>         }.addDisposableTo(rx_disposeBag)
> }
> ```
> 
> }

**Comment by tuannguyenanh177** [comment]
Sorry, i forget this:

```
self.backButton
        .rx_tap
        .subscribeNext {[unowned self] in
            self.navigationController?.popViewControllerAnimated(true)
        }.addDisposableTo(rx_disposeBag)
```

Close

**Comment by ashfurrow** [comment]
Glad you got it figured out!
