### ISSUE TITLE
Swift 3 2.0.0 CocoaPods release?

### ISSUE THREAD

**Issue by DenTelezhkin** [RxSwiftCommunity/NSObject-Rx#27]
Hey guys! 

It seems like Swift 3 compatible version of the framework has been already completed, and even podspec is updated, however there is no release on CocoaPods, are you planning to ship 2.0.0?

**Comment by ashfurrow** [comment]
Aye, sounds like a good idea :+1: I'll get on that this morning, thanks for the nudge.

**Comment by ashfurrow** [comment]
Should be okay now, let me know if you run into issues :+1:
