### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tcurdt** [RxSwiftCommunity/NSObject-Rx#30]
The latest release has

```
github "ReactiveX/RxSwift" "develop"
```

and I would like to use it with

```
github "ReactiveX/RxSwift" "3.2.0"
```

which is a bit of a problem.

**Comment by tcurdt** [comment]
I've updated the dep to `~> 3.0.0` which seems to work fine.

**Comment by RafaelPlantard** [comment]
Released and pushed to CocoaPods:
https://github.com/RxSwiftCommunity/NSObject-Rx/releases/tag/2.3.0
