### ISSUE TITLE
rx.disposeBag may be using wrong address 

### ISSUE THREAD

**Issue by grinder81** [RxSwiftCommunity/NSObject-Rx#47]
I think `rx.disposeBag` is doing some wrong memory stuff. Take a look at this post. I'm investigating now but might be helpful if you take a look as well. 

https://github.com/ReactiveX/RxSwift/issues/1439

Check kzaher comment:

> Usually what happens is that somebody is using objc_getAssociatedObject and objc_setAssociatedObject inside rx extension in this form objc_getAssociatedObject(self, ... vs the correct objc_getAssociatedObject(base, ....
> 
> Because Swift has struct reusing, those two facts combined usually results in that kind of behavior.

**Comment by ashfurrow** [comment]
Yup, gotcha. That's tricky – I think you're right that the struct is getting copied and the address used by `objc_get/setAssociatedObject`. Hmm. We may have to remove support for non-reference-types. This was introduced in [this pr](https://github.com/RxSwiftCommunity/NSObject-Rx/pull/41). I think adding a `: class` constraint to the `HasDisposeBag` protocol should fix the issue (while removing the ability to use this on value types). 

What do you think? Up for a pull request? Thanks again for opening the issue!

**Comment by grinder81** [comment]
Right now I'm doing some more investigation, I'll update when I'm done but I think that's the issue.

**Comment by ashfurrow** [comment]
Cool, thanks! Let us know what you find 👍

**Comment by grinder81** [comment]
Ok, I did quite an investigation. 

- I removed this pod completely and made sure there is no `rx.disposeBag` in my code 
- Replaced `rx.disposeBag` by `self.disposeBag` 

But still, I'm seeing that issue. Which means I can't blame this pod for memory leaking. 

However, I think that need to be fixed. I'll try to put a PR soon.

**Comment by ashfurrow** [comment]
Awesome, I look forward to it 👍

**Comment by grinder81** [comment]
PR is up! Discuss and comment there. 

Thanks

**Comment by ashfurrow** [comment]
Closed by #48, and released to CocoaPods as 4.0.0. Thanks again!
