### ISSUE TITLE
Support for RxSwift 4.0

### ISSUE THREAD

**Issue by kdawgwilk** [RxSwiftCommunity/NSObject-Rx#51]
Currently had to remove this lib to migrate to RxSwift 4.0

**Comment by ashfurrow** [comment]
Maybe you’re available to submit a pull request?

**Comment by kdawgwilk** [comment]
It was easier to remove the one place I was using it currently.  Just opened this to track the status for others

**Comment by ashfurrow** [comment]
Okay. FYI there is a PR to update this, planning to merge later today: https://github.com/RxSwiftCommunity/NSObject-Rx/pull/50 In the mean time, anyone can point to the fork.
