### ISSUE TITLE
swift 5 adapter

### ISSUE THREAD

**Issue by zjw7sky** [RxSwiftCommunity/NSObject-Rx#66]

**Comment by wikwie** [comment]
Will be very nice to have NSObject-Rx updated to the newest Swift version, since it's the only one library left in my project that hasn't been updated yet and I'm forced to copy files manually.

**Comment by Sethmr** [comment]
It is the only sdk in my setup that is not on Swift 5 as well.

**Comment by Vkt0r** [comment]
Closing this as [5.0.1](https://github.com/RxSwiftCommunity/NSObject-Rx/releases/tag/5.0.1) was released.
