### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/NSObject-Rx#7]
Our [quality index](https://cocoapods.org/pods/NSObject+Rx/quality) is taking a hit:

<img width="805" alt="screen shot 2015-11-21 at 11 49 26 am" src="https://cloud.githubusercontent.com/assets/498212/11319475/fbb5b7f2-9045-11e5-8642-da3f8e01f1ad.png">

**Comment by freak4pc** [comment]
Looks like this isn't applied to the repo anymore so I will mark it as resolved
