### ISSUE TITLE
NSObject-Rx version 5.0.0 released?

### ISSUE THREAD

**Issue by tantakan** [RxSwiftCommunity/NSObject-Rx#72]
I checked 5.0.0 in Changelog
https://github.com/RxSwiftCommunity/NSObject-Rx/blob/master/Changelog.md

but 5.0.0 tag does not release yet

**Comment by kingcos** [comment]
I found this, too.

Why not release it & publish it to CocoaPods? 😊

**Comment by ashfurrow** [comment]
It was probably an oversight – I'll take a look this afternoon.

**Comment by ashfurrow** [comment]
Okay! That's tagged and released to CocoaPods trunk. /cc @freak4pc 

Thanks for opening the issue!

**Comment by freak4pc** [comment]
Probably an oversight as @ashfurrow mentioned. Did you publish ?

**Comment by ashfurrow** [comment]
I did, though I _just_ did a tag and not the GitHub release (I just followed-up with that).
