### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ky1vstar** [RxSwiftCommunity/NSObject-Rx#87]
`NSObject+RX` v5.2.0 is NOT compatible with `RxSwift` v6.1.0 due to `~> 6.0.0` dependency version. There is a [commit](https://github.com/RxSwiftCommunity/NSObject-Rx/commit/bf2dfaac2cb72840fc5938029a3e8964f7ada1ba) that fixes it, but new version haven't been released yet. Can you please release a new one?

**Comment by ashfurrow** [comment]
Yup, makes sense. Let me get on this...

**Comment by ashfurrow** [comment]
Okay! 5.2.1 is released: https://github.com/RxSwiftCommunity/NSObject-Rx/commit/9d1967fb5f501f77d2ecfeb4f569a5f65a69a33c

**Comment by ky1vstar** [comment]
Thanks a lot!
